/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package greedycoloringgraph;
import org.apache.commons.collections15.Transformer;
import edu.uci.ics.jung.algorithms.layout.CircleLayout;
import edu.uci.ics.jung.algorithms.layout.Layout;
import edu.uci.ics.jung.graph.UndirectedSparseGraph;
import edu.uci.ics.jung.visualization.*;
import edu.uci.ics.jung.visualization.control.DefaultModalGraphMouse;
import edu.uci.ics.jung.visualization.control.ModalGraphMouse;
import edu.uci.ics.jung.visualization.decorators.ToStringLabeller;
import edu.uci.ics.jung.visualization.renderers.Renderer;
import static edu.uci.ics.jung.visualization.renderers.Renderer.VertexLabel.Position.N;
import edu.uci.ics.jung.visualization.transform.shape.GraphicsDecorator;
import greedycoloringgraph.JungLearning.MyRenderer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Paint;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
/**
 *
 * @author AtlantisSeeker
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    
    private static final String[] warna = {
        "", "Biru", "Merah", "Hijau", "Magenta", "Kuning", "Pink", "Oranye", "Abu"
    };
    
    List<Sisi> sisi = new ArrayList<>(Arrays.asList());
    UndirectedSparseGraph<Verteks, String> g = new UndirectedSparseGraph<>();
    ArrayList<String> berwarna = new ArrayList<String>();
    Verteks[] ArrayVerteks = new Verteks[10];
    int countV=0;
    int countE =0 ;
    public Gui() {
        initComponents();
        jPanel_jung.setVisible(false);
        jButton_hitung.setEnabled(true);
        jButton_reset.setEnabled(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox_simpul = new javax.swing.JComboBox<>();
        jLabel_testing = new javax.swing.JLabel();
        jButton_hitung = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jLblJudul = new javax.swing.JLabel();
        jPanel_jung = new javax.swing.JPanel();
        jLabel_simpul1 = new javax.swing.JLabel();
        jLabel_sisi = new javax.swing.JLabel();
        jTextField_vertex1 = new javax.swing.JTextField();
        jTextField_vertex2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_tambah_sisi = new javax.swing.JButton();
        jButton_tambahSimpul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Greedy Graph");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_simpul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox_simpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_simpulActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_simpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 57, -1));

        jLabel_testing.setText("Testing");
        jPanel1.add(jLabel_testing, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jButton_hitung.setText("Hitung");
        jButton_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLblJudul.setFont(new java.awt.Font("Altair", 1, 24)); // NOI18N
        jLblJudul.setText("Aplikasi Greedy Coloring Graph");
        jPanel1.add(jLblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jPanel_jung.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel_jungLayout = new javax.swing.GroupLayout(jPanel_jung);
        jPanel_jung.setLayout(jPanel_jungLayout);
        jPanel_jungLayout.setHorizontalGroup(
            jPanel_jungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel_jungLayout.setVerticalGroup(
            jPanel_jungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_jung, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 102, -1, -1));

        jLabel_simpul1.setText("Masukkan banyak verteks (simpul) : ");
        jPanel1.add(jLabel_simpul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 102, -1, -1));

        jLabel_sisi.setText("Masukkan banyak sisi (Edge) :");
        jPanel1.add(jLabel_sisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jTextField_vertex1.setText("vertex 1");
        jTextField_vertex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_vertex1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_vertex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jTextField_vertex2.setText("vertex 2");
        jPanel1.add(jTextField_vertex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel1.setText("Sisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jButton_tambah_sisi.setText("Tambah Edge");
        jButton_tambah_sisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambah_sisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_tambah_sisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jButton_tambahSimpul.setText("Tambah Simpul");
        jButton_tambahSimpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahSimpulActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_tambahSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void jComboBox_simpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_simpulActionPerformed
        int simpul = Integer.parseInt((String)jComboBox_simpul.getSelectedItem());
        simpul=simpul*(simpul-1)/2;
        jLabel1.setText("Jumlah maksimum sisi : "+simpul);
    }//GEN-LAST:event_jComboBox_simpulActionPerformed
        
    private void jButton_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hitungActionPerformed
        jPanel_jung.removeAll();
        int N = Integer.parseInt((String)jComboBox_simpul.getSelectedItem());
        int M = sisi.size();
        Graph graph = new Graph(sisi, N);
        
//===============================================================================================//        
    //memilih warna simpul dengan greedy
    
        Map<Integer, Integer> result = new HashMap<>();
        //menaruh warna satu persatu
        for(int i = 0; i<N; i++){
            Set<Integer> assigned = new TreeSet<>();
            
            //cek warna pada simpul tetangga
            for(int j:graph.adjList.get(i)){
                if(result.containsKey(j)){
                    assigned.add(result.get(j));
                }
            }
            
            //cek warna yang bisa dipake dari indeks pertama
            int warna = 1;
            for(Integer c: assigned){
                if (warna !=c){
                    break;
                }
                warna++;
            }
            
            //masukkan simpul ke-i
            result.put(i, warna);
        }
        //hasil pewarnaan
        for(int k=0; k<N; k++){
            System.out.println("Color of vertex "+k+" is "+warna[result.get(k)]);
            berwarna.add(warna[result.get(k)]);
            ArrayVerteks[k].setWarna(warna[result.get(k)]);
            g.addVertex(ArrayVerteks[k]);
       }
        //testing
        for(int k=0; k<N; k++){
            System.out.println(result.get(k));
        }
        for(int l=0; l<berwarna.size();l++){
            System.out.println(berwarna.get(l));
        }
//===============================================================================================//
//        int ulang = Integer.parseInt((String)jComboBox_simpul.getSelectedItem());
//        for(int i=0;i<ulang;i++){
//            Verteks v = new Verteks();
//            ArrayVerteks[i]=v;
//        }

        VisualizationViewer<Verteks, String> vv = new VisualizationViewer<>(new CircleLayout<>(g), new Dimension(470,370));
        
        Transformer<Verteks,Paint> vertexColor = new Transformer<Verteks,Paint>() {
            @Override public Paint transform(Verteks i) {
                if(i.getWarna().equalsIgnoreCase("biru")) return Color.blue;
                else if (i.getWarna().equalsIgnoreCase("merah")) return Color.red;
                else if (i.getWarna().equalsIgnoreCase("hijau")) return Color.green;
                else if (i.getWarna().equalsIgnoreCase("magenta")) return Color.magenta;
                else if (i.getWarna().equalsIgnoreCase("kuning")) return Color.yellow;
                else if (i.getWarna().equalsIgnoreCase("pink")) return Color.pink;
                else if (i.getWarna().equalsIgnoreCase("oranye")) return Color.orange;
                else if (i.getWarna().equalsIgnoreCase("abu")) return Color.lightGray;
                return Color.black;
            }
        };
        
        

        Transformer<Verteks,String> stringer = new Transformer<Verteks,String>(){
             public String transform(Verteks args) {
                 return "Edge"+args.getVerteks();
             }
         };
//        vv.getRenderContext().setVertexLabelTransformer(new ToStringLabeller());
//        transformer = new Transformer<Verteks, String>() {
//          @Override public String transform(String arg0) { return arg0; }
//        };
//        vv.getRenderContext().setEdgeLabelTransformer(transformer);
        vv.getRenderContext().setVertexLabelTransformer(stringer);
        vv.setBackground(Color.white);
        vv.getRenderContext().setVertexFillPaintTransformer(vertexColor);


//        vv.getRenderer().setVertexRenderer(
//                new Renderer<String, String>
//        );
        
        final DefaultModalGraphMouse<String,Number> graphMouse = new DefaultModalGraphMouse<>();
        vv.setGraphMouse(graphMouse);
        graphMouse.setMode(ModalGraphMouse.Mode.PICKING);
        
        
        
        jPanel_jung.setLayout(new FlowLayout());
        jPanel_jung.add(vv);
        jPanel_jung.setVisible(true);
        
    }//GEN-LAST:event_jButton_hitungActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        jLabel_testing.setText("test");
        jPanel_jung.setVisible(false);
        jPanel_jung.removeAll();
        jButton_hitung.setEnabled(true);
        sisi.clear();
        for(int i=0; i<countE; i++){
            g.removeEdge("Edge"+i);
        }
//        for(int i=0; i<Integer.parseInt((String)jComboBox_simpul.getSelectedItem()); i++){
//            g.removeVertex(""+i);
//        }
        countE=0;
        countV=0;
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jTextField_vertex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_vertex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_vertex1ActionPerformed

    private void jButton_tambah_sisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambah_sisiActionPerformed
        try {
            int x = Integer.parseInt((String)jTextField_vertex1.getText());
            int y = Integer.parseInt((String)jTextField_vertex2.getText());
            jLabel_testing.setText("Angkanya "+x+" dan "+y);
            sisi.add(new Sisi(x,y));
//            g.addEdge("Sisi"+count, new Verteks(), new Verteks());
//            g.addEdge("Edge"+count, ""+x, ""+y);
            sisi.add(new Sisi(x,y));
            g.addEdge("Sisi"+countE, ArrayVerteks[x], ArrayVerteks[y]);
            System.out.println(sisi);
            countE++;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka saja");
        }    
    }//GEN-LAST:event_jButton_tambah_sisiActionPerformed

    private void jButton_tambahSimpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahSimpulActionPerformed
        for(int i=0;i<Integer.parseInt((String)jComboBox_simpul.getSelectedItem());i++){
            Verteks v = new Verteks((String)jComboBox_simpul.getSelectedItem(),"");
            ArrayVerteks[i]=v;
        }
        
    }//GEN-LAST:event_jButton_tambahSimpulActionPerformed
    /**
     * @param args the command line arguments
     */
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_hitung;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_tambahSimpul;
    private javax.swing.JButton jButton_tambah_sisi;
    private javax.swing.JComboBox<String> jComboBox_simpul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_simpul1;
    private javax.swing.JLabel jLabel_sisi;
    private javax.swing.JLabel jLabel_testing;
    private javax.swing.JLabel jLblJudul;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_jung;
    private javax.swing.JTextField jTextField_vertex1;
    private javax.swing.JTextField jTextField_vertex2;
    // End of variables declaration//GEN-END:variables
}
